# Generated by Django 5.2 on 2025-05-02 15:52

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='pays',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
