# Generated by Django 5.2 on 2025-05-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0003_utilisateur_pays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structuresante',
            name='role',
        ),
        migrations.RemoveField(
            model_name='structuresante',
            name='status',
        ),
        migrations.AddField(
            model_name='structuresante',
            name='valide',
            field=models.BooleanField(default=False),
        ),
    ]
