# Generated by Django 5.2 on 2025-05-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0004_remove_structuresante_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrateur',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='structuresante',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
