# Generated by Django 5.2 on 2025-05-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0005_alter_administrateur_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recepteur',
            field=models.CharField(max_length=255),
        ),
    ]
