# Generated by Django 5.2 on 2025-05-03 23:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0006_alter_notification_recepteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='medecin',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='medecin',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medecin_created', to='dmap_app.structuresante'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medecin_updated', to='dmap_app.structuresante'),
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs_updated', to='dmap_app.structuresante'),
        ),
    ]
