# Generated by Django 5.2 on 2025-05-04 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0007_remove_utilisateur_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='archiver',
            field=models.BooleanField(default=False),
        ),
    ]
