# Generated by Django 5.2 on 2025-05-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0008_utilisateur_archiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossiermedical',
            name='statut',
        ),
        migrations.AddField(
            model_name='patient',
            name='a_dossierMedical',
            field=models.BooleanField(default=False),
        ),
    ]
