# Generated by Django 5.2 on 2025-05-04 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0009_remove_dossiermedical_statut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='created_by',
        ),
    ]
