# Generated by Django 5.2 on 2025-05-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0010_remove_consultation_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuresante',
            name='archiver',
            field=models.BooleanField(default=False),
        ),
    ]
