# Generated by Django 5.2 on 2025-05-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0011_structuresante_archiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='qr_code_expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='qr_code_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
