# Generated by Django 5.2 on 2025-05-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0012_patient_qr_code_expire_at_patient_qr_code_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='identifiant',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
