# Generated by Django 5.2 on 2025-05-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0013_patient_identifiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='identifiant',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
