# Generated by Django 5.2 on 2025-05-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0014_alter_patient_identifiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='complet',
            field=models.BooleanField(default=False),
        ),
    ]
