# Generated by Django 5.2 on 2025-05-07 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0015_dossiermedical_complet'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeCarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='En attente', max_length=50)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmap_app.patient')),
            ],
        ),
    ]
