# Generated by Django 5.2 on 2025-05-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0016_demandecarte'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='archiver',
            field=models.BooleanField(default=False),
        ),
    ]
