# Generated by Django 5.2 on 2025-05-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0017_administrateur_archiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuresante',
            name='bloquer',
            field=models.BooleanField(default=False),
        ),
    ]
