# Generated by Django 5.2 on 2025-05-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0018_structuresante_bloquer'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='bloquer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='bloquer',
            field=models.BooleanField(default=False),
        ),
    ]
