# Generated by Django 5.2 on 2025-05-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0019_administrateur_bloquer_utilisateur_bloquer'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='lu',
            field=models.BooleanField(default=False),
        ),
    ]
