# Generated by Django 5.2 on 2025-05-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0020_notification_lu'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='role',
            field=models.CharField(default='Administrateur', max_length=15),
        ),
    ]
