# Generated by Django 5.2 on 2025-05-14 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0022_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandecarte',
            name='statut',
        ),
    ]
