# Generated by Django 5.2 on 2025-05-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0023_remove_demandecarte_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrateur',
            name='archiver',
        ),
        migrations.RemoveField(
            model_name='structuresante',
            name='archiver',
        ),
        migrations.AlterField(
            model_name='administrateur',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='structuresante',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
