# Generated by Django 5.2 on 2025-05-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0024_remove_administrateur_archiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='archiver',
        ),
    ]
