# Generated by Django 5.2 on 2025-05-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0026_passwordresettokenmedecin'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuresante',
            name='archiver',
            field=models.BooleanField(default=False),
        ),
    ]
