# Generated by Django 5.2 on 2025-05-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0027_structuresante_archiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='archiver',
            field=models.BooleanField(default=False),
        ),
    ]
