# Generated by Django 5.1.2 on 2025-05-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0028_utilisateur_archiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecarte',
            name='statut',
            field=models.CharField(default='En attente', max_length=20),
        ),
    ]
