# Generated by Django 5.1.2 on 2025-05-19 01:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0029_demandecarte_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='date_debut',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='statut',
            field=models.CharField(default='En attente', max_length=20),
        ),
    ]
