# Generated by Django 5.1.2 on 2025-05-19 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0030_prescription_date_debut_prescription_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='statut',
        ),
    ]
