# Generated by Django 5.2 on 2025-05-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0031_remove_prescription_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structuresante',
            name='archiver',
        ),
    ]
