# Generated by Django 5.2 on 2025-05-21 16:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0032_remove_structuresante_archiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentmedical',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='documentmedical',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='documentmedical',
            name='nom_original',
        ),
        migrations.RemoveField(
            model_name='documentmedical',
            name='path',
        ),
        migrations.RemoveField(
            model_name='documentmedical',
            name='url',
        ),
        migrations.AddField(
            model_name='documentmedical',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.CreateModel(
            name='AlerteSanitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_alerte', models.DateTimeField()),
                ('description', models.TextField()),
                ('justification', models.TextField()),
                ('statut', models.CharField(default='En attente', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fichier_joint', models.FileField(blank=True, null=True, upload_to='alertes_sanitaires/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_created', to='dmap_app.medecin')),
                ('structure_sante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmap_app.structuresante')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_updated', to='dmap_app.medecin')),
            ],
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rendez_vous', models.DateTimeField()),
                ('description', models.TextField()),
                ('type_rendez_vous', models.CharField(default='Consultation', max_length=20)),
                ('statut', models.CharField(default='En attente', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous_created', to='dmap_app.medecin')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmap_app.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmap_app.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous_updated', to='dmap_app.medecin')),
            ],
        ),
    ]
