# Generated by Django 5.2 on 2025-05-21 16:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0033_remove_documentmedical_extension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertesanitaire',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_created', to='dmap_app.structuresante'),
        ),
        migrations.AlterField(
            model_name='alertesanitaire',
            name='date_alerte',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='alertesanitaire',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_updated', to='dmap_app.structuresante'),
        ),
    ]
