# Generated by Django 5.2 on 2025-05-21 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0034_alter_alertesanitaire_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertesanitaire',
            name='description',
        ),
    ]
