# Generated by Django 5.2 on 2025-05-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0035_remove_alertesanitaire_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertesanitaire',
            name='groupe_sanguin',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='quantite',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
