# Generated by Django 5.2 on 2025-05-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0036_alertesanitaire_groupe_sanguin_rendezvous_quantite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='quantite',
        ),
        migrations.AddField(
            model_name='alertesanitaire',
            name='quantite',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
