# Generated by Django 5.2 on 2025-05-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0037_remove_rendezvous_quantite_alertesanitaire_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertesanitaire',
            name='type_don',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alertesanitaire',
            name='urgence',
            field=models.BooleanField(default=False),
        ),
    ]
