# Generated by Django 5.2 on 2025-05-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0038_alertesanitaire_type_don_alertesanitaire_urgence'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='rappel_envoye',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alertesanitaire',
            name='fichier_joint',
            field=models.FileField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='alertesanitaire',
            name='type_don',
            field=models.CharField(max_length=20),
        ),
    ]
