# Generated by Django 5.1.2 on 2025-06-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmap_app', '0041_temoin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temoin',
            name='photo',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
